uwsgi:
    socket: uwsgi.sock
    master: true
    workers: 3
    harakiri: 60
    post-buffering: 8192
    pidfile: uwsgi.pid
    daemonize: uwsgi.log
    virtualenv: /home/varikin/apps/jesleestudios
    pythonpath: /home/varikin/apps/jesleestudios/dali
    module: dali.wsgi
